version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - nlp
    env_file: ./backend/.env

  nlp:
    build: ./nlp
    container_name: nlp
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
